config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 2}
  validates :assign_to, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task = Task.update(task_params)
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :assign_to, :photo)
  end

  def task_find
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Workflow WebApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'Task-favicon' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h3> Now is <%= Time.now %></h3>

app/views/partials/_tasks_form.html.erb
<%= simple_form_for @task do |f| %>
<%= f.input :title, label: "Task's title" %>
<%= f.input :description, label: "Task's description" %>
<%= f.input :assign_to, label: "Assigned to" %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.button :submit, class: "btn" %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= render 'partials/tasks_form', task: @task %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>
<%= link_to "Create new task", new_task_path %>
<% @tasks.each do |task|  %>
<div> <%= task.title %> </div>
<div> <%= task.description %> </div>
<div> <%= task.assign_to %> </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'partials/tasks_form', task: @task %>

app/views/tasks/show.html.erb
<h1>Here's task number <%= @task.id %></h1>
<div> <%= @task.title %></div>
<div> <%= @task.description %></div>
<div> <%= @task.assign_to %></div>
<div><%= cl_image_tag @task.photo, height: 300, width: 400, crop: :fill %></div>
<div>
  <i><%= link_to "", task_path,
  method: :delete,
  data: { confirm: "Are you sure?"}, class: "fas fa-trash right-top-icons" %>
</i>
</div>

<div>
  <%= link_to "Delete", task_path,
  method: :delete,
  data: { confirm: "Are you sure?"} %>
</div>
<div> <%= link_to "New task", new_task_path %></div>
<div> <%= link_to "All tasks", tasks_path %></div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>